### ISSUE TITLE
Name column in adversaries gear is abnormally wide

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#243]
The name column in adversaries gear on a book page is abnormally wide. This is particularly evident on Strongholds of Resistance. https://theouterrim.co/books/2744c440-3ad1-4f02-ac37-a8745861b4d7/

You can barely see the other columns when scrolling to the right.

![Screen Shot 2020-03-13 at 4 40 43 PM](https://user-images.githubusercontent.com/3457341/76664307-8107a000-6549-11ea-88bf-b83a42648bc1.png)

**Comment by AndreLemay** [comment]
Looks like what's happening is that all tables are made as wide as the widest table on the page (which is good), but this specific table is a weird edge case with only 2 columns (name/index), so what's happening is that the table is at least twice as wide as the screen, which means the name column takes up half the table, and thus one full screen. Since it sticks to the left edge, it's just covering up the entire visible part of the table.

Going to try introducing a max width on just the name column (since it should always be visible). Thinking a quarter of the screen width, and we'll see how that looks.
