### ISSUE TITLE
Add sufficient test coverage

### ISSUE THREAD

**Issue by duffn** [duffn/theouterrim#56]
Okay, we have CircleCI and a single test up. We should add sufficient test coverage to the app, testing the critical components and pages.

**Comment by bknowles** [comment]
Hmm. Is “converage” where “coverage” converges with “converge”?

🤣

**Comment by duffn** [comment]
NEED CONVERAGE. On Feb 23, 2020 11:24 AM, Brad Knowles <notifications@github.com> wrote:Hmm. Is “converage” where “coverage” converges with “converge”?

🤣

**Comment by AndreLemay** [comment]
@duffn Do you have any particular opposition to adding @types/jest as a dev dependency? I know we're not using typescript, but for whatever reason, VSCode's autocomplete is totally unaware of jest globals without this.

**Comment by duffn** [comment]
Totally fine with that.

**Comment by AndreLemay** [comment]
What kind of tests do we want overall? I'm thinking unit tests largely won't be too useful since we're basically just serving up static pages with a table component, and the component itself has ~79% coverage (if you exclude branch coverage).

Snapshot testing can be good, but I feel like it's going to be limited this early on, because there's likely to be a bunch of display/visual and data changes in the near future that would all require regenerating the snapshots, so the tests themselves wouldn't be terribly meaningful.

**Comment by duffn** [comment]
Good points and I'm fine with not making this a top priority for now.
